name: Update and Deploy GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Step 4: Run the Python script to fetch issues and generate index.html
      - name: Run Python script to fetch issues
        env:
          ACCESS_TOKEN_GIT: ${{ secrets.ACCESS_TOKEN_GIT }}
        run: python scripts/fetch_issues.py

      # Step 5: Upload the site files for GitHub Pages
      - name: Upload site files
        uses: actions/upload-pages-artifact@v3  # Updated to the latest version
        with:
          path: docs/  # Ensure this is the correct folder containing index.html

      # Step 6: Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5  # Updated to the latest version

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Updated to the latest version
