name: Update and Deploy GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for GitHub Pages deployment
  contents: write  # Required to access the repository content

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Step 4: Run the Python script to fetch issues and generate index.html
      - name: Run Python script to fetch issues
        env:
          ACCESS_TOKEN_GIT: ${{ secrets.ACCESS_TOKEN_GIT }}  # Pass secret as env var
        run: python scripts/fetch_issues.py

      # Step 5: Upload the generated site files
      - name: Upload site files
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/  # The folder that contains index.html

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
