name: Update and Deploy GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for GitHub Pages deployment
  contents: write  # Required to access the repository content
  pages: write     # Required to deploy to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Step 4: Run the Python script to fetch issues and generate index.html
      - name: Run Python script to fetch issues
        env:
          ACCESS_TOKEN_GIT: ${{ secrets.ACCESS_TOKEN_GIT }}
        run: python scripts/fetch_issues.py

      # Step 5: Upload site files
      - name: Upload site files
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Artifact name must match
          path: docs/  # Path to your generated site files

      # Step 6: Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # Step 7: Download the uploaded artifact before deploying
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages  # Must match the uploaded artifact name
          path: docs/  # Ensure correct path

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
